Update deploy-main.yml

diff --git a/.github/workflows/deploy-main.yml b/.github/workflows/deploy-main.yml
--- a/.github/workflows/deploy-main.yml
+++ b/.github/workflows/deploy-main.yml
@@ -1,9 +1,7 @@
 name: CI/CD - Crudzaso
-
 on:
   push:
     branches: [ main ]
-
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
@@ -11,7 +9,6 @@ jobs:
       - name: Fix git ownership
         run: |
           git config --global --add safe.directory "${{ secrets.PATH }}"
-
       - name: Executing remote SSH commands using password
         uses: appleboy/ssh-action@v0.1.6
         with:
@@ -26,5 +23,5 @@ jobs:
             echo '${{ secrets.ENV_FILE }}' > .env
             composer install --no-dev --optimize-autoloader
             composer dump-autoload
-            php artisan migrate:fresh --seed || echo "Database migration failed, skipping."
+            php artisan migrate:fresh --seed || (echo "Migrations failed, but continuing deployment" && true)
             php artisan optimize:clear
